fixed bugs

diff --git a/local-repo/listup-pathenv/init-listup-pathenv b/local-repo/listup-pathenv/init-listup-pathenv
--- a/local-repo/listup-pathenv/init-listup-pathenv
+++ b/local-repo/listup-pathenv/init-listup-pathenv
@@ -18,14 +18,21 @@ __listup_pathenv::listup_paths(){
 }
 
 listup-pathenv(){
-    if [[ -z "$1" ]] || [[ ! -d $1 ]]; then
+    if [[ -z "$1" ]]; then
         echo "USAGE: eval \$($0 \$DIR)" >&2
         return 1
     fi
 
-    local file
-    for file in $1/*; do
-        echo "typeset -U ${file:t}"
-        echo "export ${file:t}=$(__listup_pathenv::listup_paths $file):\$${file:t}"
-    done
+    if [[ -f "$1" ]]; then
+        echo "$0 error: DIR should be directory, but it's file." >&2
+        return 1
+    fi
+
+    if [[ -d "$1" ]]; then
+        local file
+        for file in $1/*; do
+            echo "typeset -U ${file:t}"
+            echo "export ${file:t}=$(__listup_pathenv::listup_paths $file):\$${file:t}"
+        done
+    fi
 }
